name: Deploy with Bun and PM2

on:
  push:
    branches:
      - master  # or your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          export PATH="$HOME/.bun/bin:$PATH"

      - name: Install PM2
        run: npm install -g pm2

      - name: Deploy to server
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@ec2-13-215-179-5.ap-southeast-1.compute.amazonaws.com "cd /home/ubuntu/DEMC-BACK && git pull && bun install && pm2 start --interpreter ~/.bun/bin/bun index.js"
