name: Deploy with Bun and PM2

on:
  push:
    branches:
      - main  # or your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ec2-13-215-179-5.ap-southeast-1.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@ec2-13-215-179-5.ap-southeast-1.compute.amazonaws.com << 'EOF'
            export PATH=$PATH:/home/ubuntu/.bun/bin:/home/ubuntu/.nvm/versions/node/$(node -v)/bin
            cd /home/ubuntu/DEMC-BACK
            git pull
            ~/.bun/bin/bun install
            /home/ubuntu/.bun/bin/pm2 start --interpreter ~/.bun/bin/bun index.js
          EOF
