name: Deploy with Bun and PM2

on:
  push:
    branches:
      - master  # or your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          export PATH="$HOME/.bun/bin:$PATH"

      - name: Install PM2
        run: npm install -g pm2

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ec2-13-215-179-5.ap-southeast-1.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@ec2-13-215-179-5.ap-southeast-1.compute.amazonaws.com "cd /home/ubuntu/DEMC-BACK && git pull && ~/.bun/bin/bun install && pm2 start --interpreter ~/.bun/bin/bun index.js"
